name: ci
on: [push]
jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=infra fmt -check
      - run: terraform -chdir=infra init -backend=false
      - run: terraform -chdir=infra validate
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r func/requirements.txt
